### ISSUE TITLE
Problem with AirMega Plugin: Continuous Syntax Errors

### ISSUE THREAD

**Issue by elevenI9** [aschaper/homebridge-airmega#9]
I've attempted to install the AirMega Homebridge plug-in maybe 15 times at this point over the course of two days; even going so far as to once re-install the entire Raspberry Pi OS I have it running on just to tidy it up in hopes it would then work.... but no luck.

I keep running into this when HomeBridge attempts to load the plugin:

[TAILING] Tailing last 15 lines for [homebridge] process (change the value with --lines option)

/home/pi/.pm2/logs/homebridge-error.log last 15 lines:

0|homebrid | SyntaxError: Invalid regular expression: /(?<=state\=)(.*?)$/: Invalid group

0|homebrid | at Authenticator.<anonymous> (/usr/local/lib/node_modules/homebridge-airmega/dist/lib/Authenticator.js:55:25)

0|homebrid | at Generator.next (<anonymous>)

0|homebrid | at fulfilled (/usr/local/lib/node_modules/homebridge-airmega/dist/lib/Authenticator.js:4:58)

0|homebrid | at <anonymous>

Does anyone have an idea how I can correct this? Would be much much appreciated, at my wit's end here

**Comment by aschzero** [comment]
Are you still receiving this error? If so, please enable debug logging by adding `"debug": true` to your JSON config and paste the output here. That will help provide more information to see what is going on. Thanks!

**Comment by bird99** [comment]
I saw a similar error also. I can reproduce it every time I start up homebridge. I had two guesses, the first was my account was using an email instead of an account number. I changed that but still no luck (same error). 

The other thought I have my account has two AirMega devices associated with it (400s and 300s), maybe that's throwing off the parsing. Let me know what I can do to help provide more information.
